version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cherrybee_book_store
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
    depends_on:
      - db
    volumes:
      - ./:/app

volumes:
  postgres_data:
